### ISSUE TITLE
Linux build at 0.3.3

### ISSUE THREAD

**Issue by reiinakano** [conda-forge/scikit-plot-feedstock#4]
@ericmjl Hey Eric I was checking out https://anaconda.org/conda-forge/scikit-plot and it seems like the linux build is stuck at 0.3.3. Would you happen to know why?

**Comment by ericmjl** [comment]
Hey @reiinakano! I'm not quite sure. Let's get @ocefpaf and @jakirkham in the discussion here, they might be able to help us figure out what's going on.

**Comment by ericmjl** [comment]
I saw @jakirkam do a circle-ci update through the conda-forge automatic services. Let's see if this fixes it.

**Comment by jakirkham** [comment]
Sorry for the trouble.

CircleCI requires that someone follow the project for the build. Normally our bot does that, but it seems like [CircleCI had some issues recently]( https://status.circleci.com/incidents/dsv8gn7gkq3z ), which may have dropped the bot from following the project. Asked the bot to follow the project again with issue ( https://github.com/conda-forge/scikit-plot-feedstock/issues/5 ) and have put together a dummy PR ( https://github.com/conda-forge/scikit-plot-feedstock/pull/6 ) to trigger a rebuild once merged.

Hopefully that fixes the issue. Please let us know if that works or not.

**Comment by reiinakano** [comment]
Thanks for the quick response guys @jakirkham @ericmjl!

**Comment by jakirkham** [comment]
FYI packages now appear to be up.
